config/routes.rb
EngineWrapper::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :usuarios
  
  root 'static_pages#inicio'
  
  
  match '/signup',		to:'usuarios#new',				via:'get'
  match '/signin', 		to:'sessions#new', 				via:'get'
  match '/signout', 	to:'sessions#destroy', 			via:'delete'

  match '/', 			to:'static_pages#inicio', 		via:'get'
  match '/lecciones',	to:'static_pages#lecciones',	via:'get'
  match '/contacto',	to:'static_pages#contacto', 	via:'get'
  
  
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :nombre, presence: true, length: { maximum:50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format:{ with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive:false }
	has_secure_password
	validates :password, length: {minimum:6}
	

	def Usuario.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Usuario.hash(token)
    	Digest::SHA1.hexdigest(token.to_s) 
  	end

  	private
			def create_remember_token
      		self.remember_token = Usuario.hash(Usuario.new_remember_token)
    	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		usuario = Usuario.find_by(email:params[:session][:email].downcase)
		if usuario && usuario.authenticate(params[:session][:password])
			sign_in usuario
			redirect_back_or usuario
		else
			flash.now[:danger] = 'email/contraseña combinacion incorrectos'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def inicio
  end

  def lecciones
  end

  def contacto
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
	before_action :signed_in_user,	only:[:index, :edit, :update]
	before_action :correct_user,		only:[:edit, :update]

  def index
    @usuarios = Usuario.paginate(page: params[:page])
  end
  
  def show
  	@usuario = Usuario.find(params[:id])
  end

  def new
  	@usuario = Usuario.new
  end

  def edit
  	@usuario = Usuario.find(params[:id])
  end

  def update
  	@usuario = Usuario.find(params[:id])
  	if @usuario.update_attributes(user_params)
  		flash[:success] = "Perfil actualizado"
      redirect_to @usuario
  	else
  		render 'edit'
  	end
  end

  def create
		@usuario = Usuario.new(user_params)
		if @usuario.save
			sign_in @usuario
			flash[:success] = "Bienvenido a SODMI! #{@usuario.nombre}"
			redirect_to @usuario
		else 
			render 'new'
		end
	end

	private

		def user_params
			params.require(:usuario).permit(:nombre,:email,:password,:password_confirmation)
		end

		def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Porfavor Ingrese a su cuenta"
      end
		end

		def correct_user
      @usuario = Usuario.find(params[:id])
      redirect_to(root_url) unless current_user?(@usuario)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
	#Return the full title on a per-page basis.
	def full_title(page_title)
		base_title = "SODMI "
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def sign_in(usuario)
    remember_token = Usuario.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    usuario.update_attribute(:remember_token, Usuario.hash(remember_token))
    self.current_user = usuario
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = Usuario.hash(cookies[:remember_token])
    @current_user ||= Usuario.find_by(remember_token: remember_token)
  end

  def current_user?(usuario)
    usuario == current_user
  end

  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    current_user.update_attribute(:remember_token,
                                  Usuario.hash(Usuario.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default) 
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def full_title(page_title)
		base_title = "SODMI"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
	#Regresa el Gravatar para el usuario actual
	def gravatar_for(usuario,options={size:50})
		gravatar_id = Digest::MD5::hexdigest(usuario.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt:usuario.nombre, class:"gravatar")
	end
end

app/views/layouts/_footer.html.haml
.navbar.navbar-fixed-bottom
	.navbar-inner
		.container
			%footer.footer
				%small 
					by Instituto Tecnologico de ciudad Guzman
			

app/views/layouts/_header.html.haml
.container
	.navbar.navbar-default{role: "navigation"}
		.navbar-header
			%button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
				%span.sr-only Toggle navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			%a.navbar-brand{href: "#"} SODMI	
		.navbar-collapse.collapse{style: "height: 1px;"}
			%ul.nav.navbar-nav.navbar-right
				%li.active= link_to "Inicio",root_path
				%li= link_to "Contacto", contacto_path
				- if signed_in?
					%li= link_to "Usuarios", usuarios_path
					%li#fat-menu.dropdown
						%a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
							Cuenta
							%b.caret
						%ul.dropdown-menu
							%li= link_to "Perfil", current_user
							%li= link_to "Lecciones",lecciones_path
							%li= link_to "Configuracion", edit_usuario_path(current_user)
							%li.divider
							%li
								= link_to "Salir", signout_path, method: "delete"
				- else
					%li= link_to "Entrar", signin_path


					

app/views/layouts/_shim.html.haml
/[if lt IE 9]<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%head
	%title= full_title(yield(:title))
	= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
	= javascript_include_tag "application", "data-turbolinks-track" => true 
	= csrf_meta_tags 
	= render 'layouts/shim'
%body
	= render 'layouts/header'
	.container
		- flash.each do |key, value|
			%div{class:"alert alert-#{key}"}=value
		= yield
		= debug(params) if Rails.env.development? 
	= render 'layouts/footer'	

app/views/layouts/shim.html.haml
/[if lt IE 9]<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/shared/_error_messages.html.haml
- if @usuario.errors.any?
	#error_explanation
		.alert.alert-danger
			El formulario contiene #{pluralize(@usuario.errors.count, "error")}.
		%ul
			- @usuario.errors.full_messages.each do |msg|
				%li
					* #{msg}

app/views/static_pages/contacto.html.haml
= provide(:title,"Contacto")
%h1 Contacto

app/views/static_pages/inicio.html.haml
.jumbotron
	= link_to	image_tag("SODMI.png", alt:"sodmi",id:"logo",class:"img-responsive")
	= link_to "REGISTRATE!", signup_path, class: "btn btn-large btn-primary center"

app/views/static_pages/lecciones.html.haml
= provide(:title,"Lecciones") 
%h1 Lecciones

app/views/usuarios/edit.html.haml
= provide(:title,"Editar perfil de usuario")
.row
	.col-md-4
	.col-md-4
		%h2.form-signin-heading Actualiza tu perfil
		=form_for @usuario, html:{class:"form-signin"} do |f|
			= render 'shared/error_messages'
			= f.text_field :nombre, 	class:"form-control", placeholder:"nombre"
			= f.text_field :email, 		class:"form-control", placeholder:"email"
			= f.password_field :password, class:"form-control", placeholder:"password"
			= f.password_field :password_confirmation, class:"form-control", placeholder:"password_confirmation"
			= f.submit "Guardar cambios", class:"btn btn-lg btn-primary btn-block"
		= gravatar_for @usuario
		= link_to "Cambiar", "http://gravatar.com/emails"
	.col-md-4	

app/views/usuarios/index.html.haml
- provide(:title,"Usuarios")
%h1 Usuarios

= will_paginate
%ul.usuario
  - @usuarios.each do |usuario|
    %li
      = gravatar_for usuario, size: 52
      = link_to usuario.nombre, usuario
= will_paginate

app/views/usuarios/new.html.haml
= provide(:title,"Registrate!")
.row
	.col-md-4
	.col-md-4	
		%h2.form-signin-heading REGISTRATE!
		= form_for @usuario, html:{class:"form-signin"} do |f|
			= render 'shared/error_messages'
			= f.text_field :nombre, 					class:"form-control", placeholder:"nombre"
			= f.text_field :email, 						class:"form-control", placeholder:"email"
			= f.password_field :password, 				class:"form-control", placeholder:"password"
			= f.password_field :password_confirmation, 	class:"form-control", placeholder:"password_confirmation"
			= f.submit "Crear", 						class:"btn btn-lg btn-primary btn-block"

		

app/views/usuarios/show.html.haml
=provide(:title,@usuario.nombre)
.row
	%aside.span4
		%section
			%h1
				= gravatar_for @usuario
				= @usuario.nombre 